# Book settings
title: Introducción a la Programación
author: Mario Sánchez
logo: imagenes/uniandes_logo.jpeg
copyright: Agosto de 2020

html:
  navbar_number_sections: true
  use_edit_page_button: false
  extra_footer: <a href="http://sistemas.uniandes.edu.co">Departamento de Ingeniería de Sistemas y Computación</a> - Universidad de los Andes
  google_analytics_id: ""
  home_page_in_navbar: true
  baseurl: http://cupi2-ip.github.io/IPBook

