# Book settings
title: Documentacion tecnica para nomina electronica
author: Felipe Serrano
logo: imagenes/uniandes_logo.jpeg
copyright: Marzo del 2021

html:
  navbar_number_sections: true
  use_edit_page_button: false
  extra_footer: <a href="https://www.saphety.com/">Nomina Electronica</a> - Saphety Colombia
  google_analytics_id: ""
  home_page_in_navbar: true
  baseurl: https://saphetycol.github.io/SinTema/portada.html

